### ISSUE TITLE
Ears and Tails are fugged.

### ISSUE THREAD

**Issue by Tk420634** [arfs4/ARFS4#47]
I'd like to state that we maybe should just fucking remove these, all of them.  Until we can get them fixed.  Jess wants to work on them, but its maybe a good idea.

#### Brief description of the issue
Ears and tail color layers are fucked for the following selections.  Assume that for ALL of our ported ears/tail that the shading is FUCKED.  Colors are showing way lighter, or just totally off spectrum.  Also, it's clear from having looked through these that a part of this is a layering issue.  The ears layer BELOW the head, so on some of these we ported the whole head, and its below the characters visual head.

EARS ONLY
-Glaceon - Color layers are backwards, whats changing color shouldn't and what isn't should.  IE flipping the layers.  There are stray pixels in the E/W facing sprites that shouldn't exist at all, including one that would go at the front of the players head.

~Eevee - Ears are offset on pixel on N/S facing.  

~Glowfen - Are up a pixel on the N/S facing and need to be brought down and in.  

~Grovyle - Face part of the sprite is totally fucked, not sure what's going on here exactly, but it didn't work.

~Tiger - E/W facing sprites are too far forward by a pixel or two, N/S facing sprites need to move up one, and in one.

~Vulpix - N facing sprite needs to come down a pixel.

~Rena - E/W sprite needs to come up maybe 2 pixels and move forward on the character maybe 1?  South facing sprite needs to come in one, and up one for both ears.  Same for north facing, even though it means they will overlap a bit.

~Elf - W/E facing need to come in a hair, maybe literally one pixel.

~Absol - Face area is totally fucked, same as the Grovyle.  The horn on the south facing sprite needs to come up maybe two pixels, and out two.

~Cutebold - E/W sprite needs to move forward two pixels, has a stray pixel in the E/W sprite ahead of the ears.  North facing sprites ned to come down two pixels and go in two.  North facing sprite needs to be... filled in?  The head is making a box of emptiness around the ears.  https://i.gyazo.com/be6795cda331044c3e9fb58d948085ea.png

~Elephant - THE TRUNK IS LITERALLY EATING THE FACE E/W.  The north facing sprite needs to be moved down one, same for the south facing sprites *ears.*  Not the trunk. https://i.gyazo.com/9b4acb0b8df97a74372e3b92e3286330.png

~Hylotl - E/W facing ears needs to move up a pixel or two.

~Luckytail - Its all fucked.  The head overlay is deleted, the tail needs to move over a pixel on the north sprite.  The south sprites tails not centered. You can see through the armpits, as if the giant tails weren't there.  Yeah.   Suggest full removal.

~Panther - South facing ears need to move up a pixel.

~Pony - N/S facing ears need to come down a pixel.

~Possom - WIDE BOY, MAN I WANNA DIE.  The E/W facing sprites need to come up a few, but MAN, HOLY SHIT PULL THOSE N/S EARS IN MAN. https://i.gyazo.com/d022293e012a5ad39c84d8d1fe64e73f.png

~Red Panda - N/S Ears need to come down a few pixels.  

~Kitsune - E/W need to move up a few pixels, and forward a few.  The south facing ears need to move up probably 2 pixels.

~Fox - E/W needs to move up a few, and forward a few.  N/S need to come down a few.

~Flareon - I don't know where to start.  Good luck. https://i.gyazo.com/fb503c2d10f701e864dd1ec0a308d1a9.png

~Lugia - See the intro.

~Goodra - Dude, Radar.  Get off the shrooms. https://i.gyazo.com/c16ba9f35f4342a8ec803bbbc31154ee.png

~Zangoose - The E/W sprites need to move back on the head a few pixels, the south facing ears need to move up a pixel.

NOW ONTO TAILS
Tail colors are okay, by the way.  Somehow.  Mostly.  Some don't need to be colorable.  Like most of the pokemon tails.  Also the tail layer is ABOVE the character layer???????????????????  Wat?

~Eevee - Needs placement fixed, and dual coloration. 

~Glaceon - Spare pixel around the foot in the e/w sprite.  Also layers above the hand?  North facing sprite is coming out of the left butt cheek.  Didn't need coloration.

~Glowfen - Looks surprisingly okay, has one spare pixel on the arm.

~Lizard tail - Why did we port this, its literally an unathi tail????

~Mantis Tail - What the fuck is this, and why does it show on the South facing sprite?

~Chimp - Needs placement fixed.

~Farwa - Placement fixing.

~Taj Old - The tail is literally shitting out of the character model on the E/W sprites. ._.  Needs placement fixed.

~Vulp (old) - Literally a vulpkanin tail.  Remove this pls.

~Wolpin - Stray pixel in the... kid...neys?  I dunno.

~Wryn - E/W sprite needs to move back a pixel or two.  I think?

~Vox - E/W sprite needs placement fixing.

~Elf - Could someone please explain to me why elf ears are in the tail selection????????????????????????????????????????????????????????????  I guess if you want to double up on your BIG LISTENING SKILLS????

~Stego - Why did I make this, kill me.  Is it broken?  No, not really.  I guess it needs a second color layer for the fucking spikes/plates.

~Vulture - Layering issue.

~Goat - SOMEHOW THESE LIKE 8 FUCKING PIXELS ARE IN THE WRONG PLACE?

~Ceratosaur - All fucked up.

~Corgi - Layering.

~Croc - LITERALLY AN UNATHI TAIL.

~Hawk - LITERALLY THE VULTURE TAIL.

~Ninetails - HOW IS THIS OKAY????  OF ALL THE TAILS TO WORK RIGHT?  WHAT.

~Lynx - Help there is a cucumber on my ass. https://i.gyazo.com/0d7e0d451bf7b4fab50912652e1adfd0.png

~Smildon - LITERALLY A CORGI TAIL

~Stich - LITERALLY A CORGI TAIL, REEE

~Zebra - Layering

~Crow - LITERALLY THE VULTURE TAIL

~Acaelius - Should be renamed to USB tail, and shouldn't have been colorable.

~Fluff Dragon - This is my tail, I keep it behind me in another existential reality.  https://i.gyazo.com/f759039eabe3a613f8ebf744ccb35996.png

~Deathclaw - https://www.youtube.com/watch?v=yUZeZNxiD-M  Also its offset facing north by a pixel.

~Flaffy - Needs to be uncolorable, and layering is fugged.

~Rattata - Needs to move up a hair facing north.

~Pikachu - Does not need coloration.  South facing sprite needs a few more pixels?

~Raichu - Remove coloring.

~Lizard (alt) - LOOK KIDS, A SEE THROUGH LIZARD TAIL????

~Renamon - LOOK KIDS, A BLOB OF ONE COLOR.

~Vulpix - No south facing sprite????

~Orca - Needs a second color layer.

~Skunk - Layering, needs a second color layer.

~Absol - Its like I have a tiny shark tail for an ass.

~Cutebold - Layering.

~Deer - Layering.

~Fennec - God I missed this tail, its fine, but I missed it so.

~Elephant - Layering.

~Hyena - Layering

~Raccoon - Is misspelled, for one.  Needs a second color layer for two.

~Rabbit - Layering.

~Fox (alt) - Layering.  Needs a second color layer.

~Snarby - Layering.

~Flareon - Spare pixel around the... toe...?

~Lugia - Uuuuuuuuuh.  Maybe... just... remove this one...

~Pig - Wholesome, for 4 pixels.  But also needs layers fixed.

~Goodra - Layering.

~Porcupine - SCREAM, needs to be moved around a LOT.  Probably shouldn't be colorable...?

~Zangoose - Needs to be moved, and not be just a generic blob of color.

WINGS, BECAUSE I FORGOT THOSE.

~Bat - We already had these.
~Bee - WE ALREADY HAD THESE?
~Dragon - SAME AS BAT????????
~Harpy - THESE ARE JUST WEIRD, NOTHING WRONG WITH THEM THO I GUESS.  EXCEPT WE ALREADY HAD THEM!
~Miria - HOW ABOUT THAT, THESE ARE BAT WINGS!

~Firefly - JESUS CHRIST, THAT AIN'T A FUCKING FIREFLY https://i.gyazo.com/ff6b0bec25152715aee08db84a66be0f.png

~Tentacle - Needs posistion shifting on the E/W sprite.

~ALL BUTTERFLY WINGS - Need to be moved or trimmed for layering.

#### What you expected to happen
For them to color properly, be in the right place, and to look at least okay.

#### What actually happened
They all fucked up.

#### Steps to reproduce
- (Step 1) Select ear/tail/wing
- (Step 2) Select color
- (Step 3) Scream

**Comment by thingpony** [comment]
Fuckin' fixed
